// A1 ERP-HY Permission Sets
//
// Salesforce-style permission sets: a permission set is a named, reusable bundle
// of permissions. A user holds:
//   - exactly one role (which inherits from its parent chain), AND
//   - zero or more permission sets (additive, never subtractive)
//
// Use permission sets for cross-functional needs (e.g. "Approver" can be added
// to any user regardless of role). Use roles for the primary org-position
// hierarchy.

'use strict';

const PERMISSION_SETS_VERSION = 1;

const PERMISSION_SETS = Object.freeze({
  // ─────────── Foundation ───────────
  StandardUser: {
    id: 'StandardUser',
    label: 'Standard User',
    description: 'Default set for any signed-in user. Read own profile, view dashboards, log time, view own tasks.',
    isSystem: true,
    permissions: Object.freeze([
      'system.org.read',
      'security.user.read',
      'projects.task.read',
      'projects.task.update',
      'projects.time.read',
      'projects.time.create',
      'projects.time.update',
      'reports.dashboard.read',
    ]),
  },
  MobileAccess: {
    id: 'MobileAccess',
    label: 'Mobile App Access',
    description: 'Allow login from mobile devices.',
    isSystem: true,
    permissions: Object.freeze([]),
  },

  // ─────────── Cross-functional capability sets ───────────
  Approver: {
    id: 'Approver',
    label: 'Approver',
    description: 'Approve deals, quotes, POs, bills, payroll, time off, contracts. This is a capability set, not a role.',
    isSystem: true,
    permissions: Object.freeze([
      'crm.deal.approve',
      'crm.quote.release',
      'purchase.po.approve',
      'finance.bill.approve',
      'hr.leave.approve',
      'hr.contract.approve',
      'hr.payroll.approve',
      'projects.time.approve',
    ]),
  },
  AIEnabled: {
    id: 'AIEnabled',
    label: 'AI Enabled',
    description: 'Allow the user to invoke the AI Copilot and run agents within a governed scope.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.copilot.use',
      'ai.copilot.legal',
      'ai.copilot.accounting',
      'ai.agent.run',
    ]),
  },
  AIMutator: {
    id: 'AIMutator',
    label: 'AI Mutator',
    description: 'Allow Copilot to propose mutations. Still requires a human approver with the matching action permission.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.copilot.mutate',
    ]),
  },
  AIPowerUser: {
    id: 'AIPowerUser',
    label: 'AI Power User',
    description: 'AI Enabled + AI Mutator + ability to configure Copilot topics and run evaluations.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.copilot.use',
      'ai.copilot.legal',
      'ai.copilot.accounting',
      'ai.copilot.mutate',
      'ai.copilot.configure',
      'ai.agent.read',
      'ai.agent.run',
      'ai.agent.runlog.read',
      'ai.evaluation.read',
      'ai.evaluation.run',
      'ai.prompt.read',
      'ai.prompt.update',
      'ai.fallback.read',
      'ai.budget.read',
    ]),
  },
  AgentDeveloper: {
    id: 'AgentDeveloper',
    label: 'Agent Developer',
    description: 'Create, edit, and version AI agent definitions, register tools, and run evaluations. Cannot deploy to production.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.agent.read',
      'ai.agent.create',
      'ai.agent.update',
      'ai.agent.version',
      'ai.agent.schedule',
      'ai.agent.pause',
      'ai.agent.scope.read',
      'ai.agent.scope.update',
      'ai.agent.runlog.read',
      'ai.agent.runlog.export',
      'ai.tool.read',
      'ai.tool.update',
      'ai.evaluation.read',
      'ai.evaluation.run',
      'ai.prompt.read',
      'ai.prompt.update',
      'ai.fallback.read',
      'ai.fallback.update',
      'ai.budget.read',
    ]),
  },
  AgentOperator: {
    id: 'AgentOperator',
    label: 'Agent Operator',
    description: 'Run, pause, and inspect AI agent runs. Read-only on definitions and tools.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.agent.read',
      'ai.agent.run',
      'ai.agent.pause',
      'ai.agent.scope.read',
      'ai.agent.runlog.read',
      'ai.tool.read',
      'ai.evaluation.read',
      'ai.budget.read',
    ]),
  },
  AgentDeployer: {
    id: 'AgentDeployer',
    label: 'Agent Deployer',
    description: 'Deploy and rollback AI agent versions to production (critical, dual-control).',
    isSystem: true,
    permissions: Object.freeze([
      'ai.agent.deploy',
      'ai.agent.rollback',
      'ai.agent.delete',
    ]),
  },
  AIGovernance: {
    id: 'AIGovernance',
    label: 'AI Governance',
    description: 'Manage AI token/cost budgets and fallback rules org-wide.',
    isSystem: true,
    permissions: Object.freeze([
      'ai.budget.read',
      'ai.budget.update',
      'ai.fallback.read',
      'ai.fallback.update',
      'ai.prompt.read',
      'ai.prompt.update',
    ]),
  },
  SensitiveDataReader: {
    id: 'SensitiveDataReader',
    label: 'Sensitive Data Reader',
    description: 'Read access to PII and confidential fields. Use sparingly; required for HR, finance close, and compliance investigations.',
    isSystem: true,
    permissions: Object.freeze([
      'hr.employee.pii.read',
      'docs.evidence.read',
      'compliance.legal.read',
    ]),
  },
  PIIEditor: {
    id: 'PIIEditor',
    label: 'PII Editor',
    description: 'Edit employee PII. Highly sensitive — restricted to HR and compliance.',
    isSystem: true,
    permissions: Object.freeze([
      'hr.employee.pii.read',
      'hr.employee.pii.update',
    ]),
  },

  // ─────────── Finance sets ───────────
  FinanceOperator: {
    id: 'FinanceOperator',
    label: 'Finance Operator',
    description: 'Day-to-day finance: invoices, bills, payments, bank, journal, tax.',
    isSystem: true,
    permissions: Object.freeze([
      'finance.coa.read',
      'finance.journal.read',
      'finance.journal.create',
      'finance.journal.update',
      'finance.journal.post',
      'finance.invoice.read',
      'finance.invoice.create',
      'finance.invoice.update',
      'finance.invoice.issue',
      'finance.bill.read',
      'finance.bill.create',
      'finance.bill.update',
      'finance.payment.read',
      'finance.payment.create',
      'finance.bank.read',
      'finance.bank.reconcile',
      'finance.tax.read',
      'finance.vat_return.read',
      'finance.vat_return.prepare',
      'finance.budget.read',
      'finance.einvoice.read',
      'finance.einvoice.issue',
    ]),
  },
  FinancePeriodAdmin: {
    id: 'FinancePeriodAdmin',
    label: 'Finance Period Admin',
    description: 'Lock/unlock accounting periods and close fiscal year.',
    isSystem: true,
    permissions: Object.freeze([
      'finance.period.lock',
      'finance.period.unlock',
      'finance.year_end.close',
    ]),
  },
  TaxFiler: {
    id: 'TaxFiler',
    label: 'Tax Filer',
    description: 'Permission to file the VAT return with the tax authority.',
    isSystem: true,
    permissions: Object.freeze([
      'finance.vat_return.file',
      'finance.tax.update',
      'reports.tax.read',
      'reports.tax.export',
    ]),
  },

  // ─────────── CRM sets ───────────
  CRMOperator: {
    id: 'CRMOperator',
    label: 'CRM Operator',
    description: 'Leads, deals, accounts, contacts, activities, pipeline.',
    isSystem: true,
    permissions: Object.freeze([
      'crm.lead.read',
      'crm.lead.create',
      'crm.lead.update',
      'crm.lead.delete',
      'crm.lead.assign',
      'crm.lead.import',
      'crm.lead.export',
      'crm.account.read',
      'crm.account.create',
      'crm.account.update',
      'crm.account.delete',
      'crm.account.merge',
      'crm.contact.read',
      'crm.contact.create',
      'crm.contact.update',
      'crm.contact.delete',
      'crm.deal.read',
      'crm.deal.create',
      'crm.deal.update',
      'crm.deal.delete',
      'crm.deal.assign',
      'crm.deal.export',
      'crm.quote.read',
      'crm.quote.create',
      'crm.quote.update',
      'crm.quote.delete',
      'crm.quote.send',
      'crm.quote.accept',
      'crm.activity.read',
      'crm.activity.create',
      'crm.activity.update',
      'crm.activity.delete',
      'crm.pipeline.read',
      'crm.pipeline.update',
      'crm.customer_360.read',
    ]),
  },

  // ─────────── Inventory sets ───────────
  InventoryOperator: {
    id: 'InventoryOperator',
    label: 'Inventory Operator',
    description: 'Stock, products, warehouses, lots.',
    isSystem: true,
    permissions: Object.freeze([
      'inv.product.read',
      'inv.product.create',
      'inv.product.update',
      'inv.product.import',
      'inv.product.export',
      'inv.warehouse.read',
      'inv.stock.read',
      'inv.stock.receive',
      'inv.stock.deliver',
      'inv.stock.transfer',
      'inv.stock.adjust',
      'inv.stock.scrap',
      'inv.stock.count',
      'inv.valuation.read',
      'inv.lot.read',
      'inv.lot.update',
    ]),
  },
  InventoryAdmin: {
    id: 'InventoryAdmin',
    label: 'Inventory Admin',
    description: 'Manage warehouses and run valuation.',
    isSystem: true,
    permissions: Object.freeze([
      'inv.product.delete',
      'inv.warehouse.update',
      'inv.valuation.run',
    ]),
  },

  // ─────────── Purchase sets ───────────
  PurchaseOperator: {
    id: 'PurchaseOperator',
    label: 'Purchase Operator',
    description: 'RFQs, POs, receipts, returns, vendor master.',
    isSystem: true,
    permissions: Object.freeze([
      'purchase.vendor.read',
      'purchase.vendor.create',
      'purchase.vendor.update',
      'purchase.vendor_360.read',
      'purchase.rfq.read',
      'purchase.rfq.create',
      'purchase.rfq.update',
      'purchase.rfq.delete',
      'purchase.rfq.send',
      'purchase.po.read',
      'purchase.po.create',
      'purchase.po.update',
      'purchase.po.send',
      'purchase.po.cancel',
      'purchase.receipt.read',
      'purchase.receipt.create',
      'purchase.return.create',
      'purchase.pricelist.read',
      'purchase.analytics.read',
    ]),
  },
  PurchaseAdmin: {
    id: 'PurchaseAdmin',
    label: 'Purchase Admin',
    description: 'Vendor master hard-delete and pricelist management.',
    isSystem: true,
    permissions: Object.freeze([
      'purchase.vendor.delete',
      'purchase.pricelist.update',
    ]),
  },

  // ─────────── POS sets ───────────
  POSOperator: {
    id: 'POSOperator',
    label: 'POS Operator',
    description: 'Operate the register, record sales, manage cash drawer.',
    isSystem: true,
    permissions: Object.freeze([
      'pos.session.open',
      'pos.sale.create',
      'pos.cash.read',
      'pos.cash.manage',
      'pos.zreport.read',
      'pos.fiscal.hdm',
    ]),
  },
  POSSupervisor: {
    id: 'POSSupervisor',
    label: 'POS Supervisor',
    description: 'Close sessions, void sales, issue refunds.',
    isSystem: true,
    permissions: Object.freeze([
      'pos.session.close',
      'pos.sale.void',
      'pos.refund.create',
    ]),
  },

  // ─────────── HR sets ───────────
  HROperator: {
    id: 'HROperator',
    label: 'HR Operator',
    description: 'Employee master, contracts, attendance, leave.',
    isSystem: true,
    permissions: Object.freeze([
      'hr.employee.read',
      'hr.employee.create',
      'hr.employee.update',
      'hr.contract.read',
      'hr.contract.create',
      'hr.contract.update',
      'hr.attendance.read',
      'hr.attendance.update',
      'hr.leave.read',
      'hr.leave.request',
      'hr.recruitment.read',
      'hr.recruitment.update',
      'hr.performance.read',
      'hr.performance.update',
      'hr.fleet.read',
      'hr.fleet.update',
    ]),
  },
  PayrollOperator: {
    id: 'PayrollOperator',
    label: 'Payroll Operator',
    description: 'Run and post payroll.',
    isSystem: true,
    permissions: Object.freeze([
      'hr.payroll.read',
      'hr.payroll.run',
      'hr.payroll.post',
    ]),
  },

  // ─────────── Projects sets ───────────
  ProjectsOperator: {
    id: 'ProjectsOperator',
    label: 'Projects Operator',
    description: 'Projects, tasks, time, billing.',
    isSystem: true,
    permissions: Object.freeze([
      'projects.project.read',
      'projects.project.create',
      'projects.project.update',
      'projects.project.delete',
      'projects.task.read',
      'projects.task.create',
      'projects.task.update',
      'projects.task.delete',
      'projects.task.assign',
      'projects.time.read',
      'projects.time.create',
      'projects.time.update',
      'projects.billing.read',
      'projects.billing.update',
      'projects.profitability.read',
    ]),
  },

  // ─────────── Helpdesk sets ───────────
  DeskOperator: {
    id: 'DeskOperator',
    label: 'Helpdesk Operator',
    description: 'Service cases, replies, knowledge, SLAs.',
    isSystem: true,
    permissions: Object.freeze([
      'desk.case.read',
      'desk.case.create',
      'desk.case.update',
      'desk.case.delete',
      'desk.case.assign',
      'desk.case.escalate',
      'desk.case.resolve',
      'desk.case.close',
      'desk.reply.create',
      'desk.knowledge.read',
      'desk.sla.read',
      'desk.field_service.read',
    ]),
  },
  DeskAdmin: {
    id: 'DeskAdmin',
    label: 'Helpdesk Admin',
    description: 'Knowledge base and SLA configuration, field service dispatch.',
    isSystem: true,
    permissions: Object.freeze([
      'desk.knowledge.update',
      'desk.sla.update',
      'desk.field_service.update',
    ]),
  },

  // ─────────── Docs sets ───────────
  DocsOperator: {
    id: 'DocsOperator',
    label: 'Docs Operator',
    description: 'Document lifecycle, signatures, evidence.',
    isSystem: true,
    permissions: Object.freeze([
      'docs.document.read',
      'docs.document.create',
      'docs.document.update',
      'docs.document.export',
      'docs.template.read',
      'docs.signature.request',
      'docs.signature.sign',
      'docs.signature.decline',
      'docs.evidence.read',
      'docs.cabinet.read',
      'docs.request.read',
      'compliance.legal.review',
    ]),
  },
  DocsAdmin: {
    id: 'DocsAdmin',
    label: 'Docs Admin',
    description: 'Templates, cabinet, requested docs, signature override.',
    isSystem: true,
    permissions: Object.freeze([
      'docs.template.update',
      'docs.cabinet.update',
      'docs.request.update',
      'docs.document.delete',
      'docs.signature.override',
      'docs.evidence.export',
    ]),
  },

  // ─────────── Portal / External ───────────
  PortalCustomer: {
    id: 'PortalCustomer',
    label: 'Portal Customer',
    description: 'External customer with portal access.',
    isSystem: true,
    permissions: Object.freeze([
      'portal.storefront.read',
      'portal.cart.create',
      'portal.order.read',
      'portal.order.create',
      'portal.invoice.read',
      'portal.payment.make',
      'portal.ticket.create',
      'portal.document.read',
    ]),
  },
  PortalVendor: {
    id: 'PortalVendor',
    label: 'Portal Vendor',
    description: 'External vendor with portal access.',
    isSystem: true,
    permissions: Object.freeze([
      'purchase.rfq.read',
      'purchase.po.read',
    ]),
  },

  // ─────────── Marketing sets ───────────
  MarketingOperator: {
    id: 'MarketingOperator',
    label: 'Marketing Operator',
    description: 'Campaigns, segments, templates, consent.',
    isSystem: true,
    permissions: Object.freeze([
      'mrkt.campaign.read',
      'mrkt.campaign.create',
      'mrkt.campaign.update',
      'mrkt.campaign.delete',
      'mrkt.campaign.send',
      'mrkt.campaign.pause',
      'mrkt.campaign.duplicate',
      'mrkt.campaign.export',
      'mrkt.segment.read',
      'mrkt.segment.update',
      'mrkt.segment.preview',
      'mrkt.template.read',
      'mrkt.template.update',
      'mrkt.consent.read',
      'mrkt.consent.update',
      'mrkt.unsubscribe.read',
      'mrkt.unsubscribe.manage',
      'mrkt.landing.read',
      'mrkt.landing.update',
      'mrkt.form.read',
      'mrkt.form.update',
    ]),
  },
  MarketingAutomation: {
    id: 'MarketingAutomation',
    label: 'Marketing Automation',
    description: 'Journeys, subscriptions, lead scoring, A/B tests, marketing webhooks.',
    isSystem: true,
    permissions: Object.freeze([
      'mrkt.journey.read',
      'mrkt.journey.update',
      'mrkt.journey.publish',
      'mrkt.subscription.read',
      'mrkt.subscription.update',
      'mrkt.lead_score.read',
      'mrkt.lead_score.update',
      'mrkt.abtest.read',
      'mrkt.abtest.update',
      'mrkt.webhook.read',
      'mrkt.webhook.update',
    ]),
  },

  // ─────────── Manufacturing sets ───────────
  ManufacturingOperator: {
    id: 'ManufacturingOperator',
    label: 'Manufacturing Operator',
    description: 'BoM, work orders, work centers, quality, repairs.',
    isSystem: true,
    permissions: Object.freeze([
      'mfg.bom.read',
      'mfg.bom.update',
      'mfg.routing.read',
      'mfg.work_order.read',
      'mfg.work_order.create',
      'mfg.work_order.update',
      'mfg.work_order.release',
      'mfg.work_order.complete',
      'mfg.work_center.read',
      'mfg.work_center.update',
      'mfg.quality.read',
      'mfg.quality.update',
      'mfg.repair.read',
      'mfg.repair.update',
      'mfg.mps.read',
      'mfg.costing.read',
    ]),
  },
  ManufacturingAdmin: {
    id: 'ManufacturingAdmin',
    label: 'Manufacturing Admin',
    description: 'Destructive manufacturing actions: BoM delete/version, work order cancel, MRP, MPS, costing rollup, repair complete.',
    isSystem: true,
    permissions: Object.freeze([
      'mfg.bom.delete',
      'mfg.bom.version',
      'mfg.routing.update',
      'mfg.work_order.cancel',
      'mfg.mps.update',
      'mfg.mrp.run',
      'mfg.costing.update',
      'mfg.repair.complete',
    ]),
  },
  QualityHoldAdmin: {
    id: 'QualityHoldAdmin',
    label: 'Quality Hold Admin',
    description: 'Place lots on hold and release them (critical, dual-control).',
    isSystem: true,
    permissions: Object.freeze([
      'mfg.quality.hold',
      'mfg.quality.release',
    ]),
  },

  // ─────────── Compliance sets ───────────
  ComplianceOperator: {
    id: 'ComplianceOperator',
    label: 'Compliance Operator',
    description: 'Policies, consent, retention, legal sources, GDPR/PDPA. Read + high-sensitivity mutations only (no breach/SOX/retention-purge).',
    isSystem: true,
    permissions: Object.freeze([
      'compliance.policy.read',
      'compliance.policy.update',
      'compliance.policy.approve',
      'compliance.policy.publish',
      'compliance.control.read',
      'compliance.control.update',
      'compliance.risk.read',
      'compliance.risk.update',
      'compliance.evidence.read',
      'compliance.evidence.update',
      'compliance.vendor_assessment.read',
      'compliance.vendor_assessment.update',
      'compliance.consent.read',
      'compliance.consent.update',
      'compliance.retention.read',
      'compliance.legal.read',
      'compliance.legal.update',
      'compliance.gdpr.read',
      'compliance.gdpr.fulfill',
      'compliance.breach.read',
      'compliance.sox.read',
    ]),
  },
  ComplianceAdmin: {
    id: 'ComplianceAdmin',
    label: 'Compliance Admin',
    description: 'Destructive compliance ops: breach register update, retention purge, SOX control updates. Granted only to ComplianceOfficer + Owner, NOT to Auditor.',
    isSystem: true,
    permissions: Object.freeze([
      'compliance.retention.update',
      'compliance.retention.run',
      'compliance.breach.update',
      'compliance.sox.update',
    ]),
  },
  PilotOperator: {
    id: 'PilotOperator',
    label: 'Pilot Operator',
    description: 'Day-to-day clinic-wellness pilot operator: view templates, manage owner briefs, workbenches, and accountant reviews. The renewal/quote/closeout chain still requires role-specific grants.',
    isSystem: true,
    permissions: Object.freeze([
      'pilot.template.read',
      'pilot.template.install',
      'pilot.brief.read',
      'pilot.brief.create',
      'pilot.workbench.read',
      'pilot.workbench.create',
      'pilot.review.read',
      'pilot.review.create',
    ]),
  },
  RetentionAdmin: {
    id: 'RetentionAdmin',
    label: 'Retention Admin',
    description: 'Update data retention rules.',
    isSystem: true,
    permissions: Object.freeze([
      'compliance.retention.update',
    ]),
  },
  RetentionOperator: {
    id: 'RetentionOperator',
    label: 'Retention Operator',
    description: 'Run retention purges (Owner-approval gated).',
    isSystem: true,
    permissions: Object.freeze([
      'compliance.retention.run',
    ]),
  },
  AuditOperator: {
    id: 'AuditOperator',
    label: 'Audit Operator',
    description: 'Read and export audit data; prepare and deliver audit packets.',
    isSystem: true,
    permissions: Object.freeze([
      'security.audit.read',
      'security.audit.export',
      'security.access.review',
      'security.session.list',
      'security.session.revoke',
      'compliance.audit.prepare',
      'system.integrations.read',
    ]),
  },
  AuditDeliver: {
    id: 'AuditDeliver',
    label: 'Audit Deliver',
    description: 'Permission to deliver an audit packet externally (Owner-level).',
    isSystem: true,
    permissions: Object.freeze([
      'compliance.audit.deliver',
    ]),
  },

  // ─────────── Studio / Builder sets ───────────
  StudioBuilder: {
    id: 'StudioBuilder',
    label: 'Studio Builder',
    description: 'Custom fields, workflows, approvals, webhooks, layouts.',
    isSystem: true,
    permissions: Object.freeze([
      'studio.custom_field.read',
      'studio.custom_field.update',
      'studio.workflow.read',
      'studio.workflow.update',
      'studio.workflow.run',
      'studio.approval.read',
      'studio.approval.update',
      'studio.webhook.read',
      'studio.webhook.update',
      'studio.layout.read',
      'studio.layout.update',
    ]),
  },
  ReportBuilder: {
    id: 'ReportBuilder',
    label: 'Report Builder',
    description: 'Dashboards, reports, spreadsheet builder.',
    isSystem: true,
    permissions: Object.freeze([
      'reports.dashboard.read',
      'reports.dashboard.update',
      'reports.builder.read',
      'reports.builder.update',
      'reports.spreadsheet.read',
      'reports.spreadsheet.update',
      'analytics.snapshot.read',
      'analytics.snapshot.create',
      'analytics.snapshot.capture',
      'analytics.report.read',
      'analytics.report.write',
      'analytics.report.export',
      'analytics.monthly_series.read',
      'analytics.budget.read',
      'analytics.receivables_aging.read',
      'analytics.semantic_metrics.read',
      'analytics.role_dashboard.read',
    ]),
  },

  // ─────────── System admin sets ───────────
  SystemAdmin: {
    id: 'SystemAdmin',
    label: 'System Admin',
    description: 'Full system control except the most destructive Owner-only operations (tenant create/delete, system restore). Owner gets those via the implicit-all shortcut.',
    isSystem: true,
    permissions: Object.freeze([
      'system.org.read',
      'system.org.update',
      'system.tenant.read',
      'system.tenant.list',
      'system.tenant.update',
      'system.tenant.plan.read',
      'system.tenant.plan.update',
      'system.tenant.billing.read',
      'system.tenant.billing.update',
      'system.tenant.domain.read',
      'system.tenant.domain.update',
      'system.tenant.sso.read',
      'system.tenant.sso.update',
      'system.tenant.isolation.read',
      'system.tenant.region.update',
      'system.settings.read',
      'system.settings.update',
      'system.integrations.read',
      'system.integrations.update',
      'system.backup.read',
      'system.backup.run',
    ]),
  },
  TenantAdmin: {
    id: 'TenantAdmin',
    label: 'Tenant Admin',
    description: 'Owner-level tenant lifecycle: create, suspend, reactivate, delete, transfer, isolation policy. Composes on top of SystemAdmin.',
    isSystem: true,
    permissions: Object.freeze([
      'system.tenant.create',
      'system.tenant.suspend',
      'system.tenant.reactivate',
      'system.tenant.delete',
      'system.tenant.transfer',
      'system.tenant.isolation.update',
    ]),
  },
  TenantSupport: {
    id: 'TenantSupport',
    label: 'Tenant Support',
    description: 'Read-only tenant visibility for customer support staff. No mutations.',
    isSystem: true,
    permissions: Object.freeze([
      'system.tenant.read',
      'system.tenant.list',
      'system.tenant.plan.read',
      'system.tenant.billing.read',
      'system.tenant.domain.read',
      'system.tenant.sso.read',
      'system.tenant.isolation.read',
    ]),
  },
  UserAdmin: {
    id: 'UserAdmin',
    label: 'User Admin',
    description: 'User CRUD, role/permission set/profile assignment, sessions, MFA, API keys.',
    isSystem: true,
    permissions: Object.freeze([
      'security.user.list',
      'security.user.read',
      'security.user.create',
      'security.user.update',
      'security.user.deactivate',
      'security.user.delete',
      'security.user.reset_password',
      'security.user.impersonate',
      'security.role.read',
      'security.role.create',
      'security.role.update',
      'security.role.delete',
      'security.role.assign',
      'security.permission_set.read',
      'security.permission_set.update',
      'security.profile.read',
      'security.profile.update',
      'security.session.list',
      'security.session.revoke',
      'security.mfa.configure',
      'security.mfa.reset',
      'security.api_key.read',
      'security.api_key.create',
      'security.api_key.revoke',
    ]),
  },
  SecurityAdmin: {
    id: 'SecurityAdmin',
    label: 'Security Admin',
    description: 'Read-only user/session/audit, can revoke sessions and run access reviews.',
    isSystem: true,
    permissions: Object.freeze([
      'security.user.list',
      'security.user.read',
      'security.session.list',
      'security.session.revoke',
      'security.audit.read',
      'security.audit.export',
      'security.access.review',
    ]),
  },

  // ─────────── Read-only sets ───────────
  ReadOnly: {
    id: 'ReadOnly',
    label: 'Read Only',
    description: 'Read-only access to operational modules.',
    isSystem: true,
    permissions: Object.freeze([
      'crm.lead.read',
      'crm.account.read',
      'crm.contact.read',
      'crm.deal.read',
      'crm.quote.read',
      'crm.activity.read',
      'crm.pipeline.read',
      'crm.customer_360.read',
      'inv.product.read',
      'inv.warehouse.read',
      'inv.stock.read',
      'inv.lot.read',
      'inv.valuation.read',
      'purchase.vendor.read',
      'purchase.vendor_360.read',
      'purchase.rfq.read',
      'purchase.po.read',
      'purchase.receipt.read',
      'purchase.pricelist.read',
      'purchase.analytics.read',
      'finance.coa.read',
      'finance.journal.read',
      'finance.invoice.read',
      'finance.bill.read',
      'finance.payment.read',
      'finance.bank.read',
      'finance.tax.read',
      'finance.budget.read',
      'finance.vat_return.read',
      'finance.einvoice.read',
      'projects.project.read',
      'projects.task.read',
      'projects.time.read',
      'projects.billing.read',
      'projects.profitability.read',
      'desk.case.read',
      'desk.knowledge.read',
      'desk.sla.read',
      'docs.document.read',
      'docs.template.read',
      'docs.evidence.read',
      'docs.cabinet.read',
      'docs.request.read',
      'hr.employee.read',
      'hr.contract.read',
      'hr.attendance.read',
      'hr.leave.read',
      'hr.recruitment.read',
      'mrkt.campaign.read',
      'mrkt.segment.read',
      'mrkt.template.read',
      'mrkt.consent.read',
      'mrkt.unsubscribe.read',
      'mfg.bom.read',
      'mfg.work_order.read',
      'mfg.work_center.read',
      'mfg.quality.read',
      'mfg.repair.read',
      'reports.dashboard.read',
      'reports.financial.read',
      'reports.tax.read',
      'reports.operational.read',
      'reports.builder.read',
      'reports.spreadsheet.read',
    ]),
  },
});

function listPermissionSetIds() {
  return Object.freeze(Object.keys(PERMISSION_SETS));
}

function getPermissionSet(id) {
  return PERMISSION_SETS[id] || null;
}

function isSystemPermissionSet(id) {
  const ps = PERMISSION_SETS[id];
  return Boolean(ps && ps.isSystem);
}

module.exports = {
  PERMISSION_SETS_VERSION,
  PERMISSION_SETS,
  listPermissionSetIds,
  getPermissionSet,
  isSystemPermissionSet,
};
